### ISSUE TITLE
Add JaCoCo test plugin for Code Coverage Reporting

### ISSUE THREAD

**Issue by rorybakerfmr** [jenkinsci/cdevents-plugin#17]
As a developer, I would like code coverage reports to see what classes, methods and branch conditionals are covered by our unit tests, so that I can ensure changes to the plugin are adequately tested.

[JaCoCo](https://www.jacoco.org/jacoco/) is a widely used code coverage library for Java that can generate HTML reports as well as coverage reports for static analysis tools like SonarQube.

To use this plugin, we would need to add the plugin to `pom.xml`:
```xml
<plugin>
    <groupId>org.jacoco</groupId>
    <artifactId>jacoco-maven-plugin</artifactId>
    <version>0.8.12</version>
    <executions>
        <execution>
            <goals>
                <goal>prepare-agent</goal>
            </goals>
        </execution>
        <!-- attached to Maven test phase -->
        <execution>
            <id>report</id>
            <phase>test</phase>
            <goals>
                <goal>report</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

Once added, developers can run `mvn clean verify` to execute tests and generate the JaCoCo report. The HTML report will be available in the `target/site/jacoco` directory.

**Comment by userAdityaa** [comment]
Hello, I am new to contributing to jenkins but for the this thing we just have to add the plugins artifact id, group id, and the version that's it. If im not wrong. Can you help me with this ?

**Comment by StephenDarcy** [comment]
I will work on this :)
