### ISSUE TITLE
Incorrect null check on KinesisSink/KinesisStreamName

### ISSUE THREAD

**Issue by rorybakerfmr** [jenkinsci/cdevents-plugin#19]
https://github.com/jenkinsci/cdevents-plugin/blob/c74e07992738a7e03fa9c940b9094bffe7450c09/src/main/java/io/jenkins/plugins/cdevents/sinks/KinesisSink.java#L39-L42

The constructor currently should check if `CDEventsGlobalConfig.get().getKinesisStreamName()` is null or empty, as this is a required value to use the sink. The problem lies in the use of the logical AND operator (`&&`). If `CDEventsGlobalConfig.get().getKinesisStreamName()` is null, the second part of the condition (`CDEventsGlobalConfig.get().getKinesisStreamName().trim().isEmpty()`) will throw a NullPointerException because we are trying to call trim() on a null value. A correct null-or-empty check should use the logical OR operator (`||`). This way, if the string is null, the second part of the condition won't be evaluated, preventing the NullPointerException.

To fix: make the following change:
```java
if (CDEventsGlobalConfig.get().getKinesisStreamName() == null
        || CDEventsGlobalConfig.get().getKinesisStreamName().trim().isEmpty()) {
    throw new NullPointerException("Kinesis stream name cannot be blank");
}
```

**Comment by harshanabandara** [comment]
@rorybakerfmr I have created a PR. Please review.

**Comment by rorybakerfmr** [comment]
Looks good to me, thank you!
