### ISSUE TITLE
Optimize Repeated Method Calls

### ISSUE THREAD

**Issue by apurvagandhi** [jenkinsci/cdevents-plugin#21]
**Describe the solution you'd like**
The CDEventsGlobalConfig.get() method is called multiple times. You could call this method once and store the result in a variable, then use this variable in the subsequent lines. This makes the code cleaner and slightly more efficient.

**Comment by jes-so** [comment]
I'll grab this one.

**Comment by arjun-kshirsagar** [comment]
@rorybakerfmr Please close this issue, I have reviewed the code, it's a clean code.
