### ISSUE TITLE
Optimze the code by using StringUtils.isBlank() method

### ISSUE THREAD

**Issue by apurvagandhi** [jenkinsci/cdevents-plugin#24]
Instead of checking for null and then checking for empty, you can use Apache Commons Lang's StringUtils.isBlank() method. This should optimized the code and improve readability.

**Comment by saivarun0125** [comment]
I would like to work on this

**Comment by javedbaig** [comment]
I would like to work on this.

**Comment by javedbaig** [comment]
Please could @rorybakerfmr you help me why my pr checks are failing?

**Comment by rorybakerfmr** [comment]
Closed by https://github.com/jenkinsci/cdevents-plugin/pull/29
