### ISSUE TITLE
Update plugin BOMs and dependencies

### ISSUE THREAD

**Issue by rorybakerfmr** [jenkinsci/cdevents-plugin#5]
### This issue reserved for Fidelity Open Source Workshop

https://www.jenkins.io/doc/developer/plugin-development/dependency-management/

In order to keep this plugin up to date, we need to update it's declared dependencies. You can review the documentation at the link above for a general overview of this process.

1. Update the Jenkins core BOM:
```
mvn versions:update-parent
```

2. Update the plugin BOM (see [Jenkins bom/releases](https://github.com/jenkinsci/bom/releases)) to the latest version in the `<dependencyManagement>` section of pom.xml (at this time, the latest is **2081.v85885a_d2e5c5**):
```
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.jenkins.tools.bom</groupId>
                <artifactId>bom-2.375.x</artifactId>
                <version>LATEST VERSION GOES HERE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

3. We have a fixed dependency on `org.jenkins-ci.plugins:aws-java-sdk` that should be updated. Check the [Jenkins AWS SDK Plugin](https://plugins.jenkins.io/aws-java-sdk/releases/) releases page to find the latest version (**1.12.447-382.vda_68e2007233** at this time). Update this in the `<dependencies>` section if a new version has been released.
```
        <dependency>
            <groupId>org.jenkins-ci.plugins</groupId>
            <artifactId>aws-java-sdk</artifactId>
            <version>LATEST VERSION GOES HERE</version>
            <optional>true</optional>
        </dependency>
```

4. Test your changes and address any issues (esp. Maven Enforcer or SpotBugs issues that may arise from updates)
```
mvn clean verify
```

**Comment by utkuertunc** [comment]
@rorybakerfmr Hey Rory, I want to close this issue. I can run the app in my local with `mvn clean hpi:run` 
but as I see, `mvn clean verify` is getting error about tests. If I use -DskipTests clean verify built success. Should I use skipTests or shoul we fix that test ? 

**### Error log:**
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
Running tests for io.jenkins.plugins:cdevents:1-999999-SNAPSHOT
java.lang.InternalError 
{0x00000007151f6bc8} - klass: 'java/lang/InternalError'
 - ---- fields (total size 5 words):
 - private transient 'backtrace' 'Ljava/lang/Object;' @12  a 'java/lang/Object'[5] {0x00000007151f6bf0} (e2a3ed7e)
 - private 'detailMessage' 'Ljava/lang/String;' @16  "name is too long to represent"{0x00000007151f6b80} (e2a3ed70)
 - private 'cause' 'Ljava/lang/Throwable;' @20  a 'java/lang/InternalError'{0x00000007151f6bc8} (e2a3ed79)
 - private 'stackTrace' '[Ljava/lang/StackTraceElement;' @24  a 'java/lang/StackTraceElement'[0] {0x00000007040e5778} (e081caef)
 - private strict 'suppressedExceptions' 'Ljava/util/List;' @28  a 'java/util/Collections$EmptyList'{0x00000007040e5768} (e081caed)
 - private transient 'depth' 'I' @32  85 (55)
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (./open/src/hotspot/share/utilities/preserveException.cpp:46), pid=1916, tid=9684
#  fatal error: PreserveExceptionMark destructor expects no pending exceptions
#
# JRE version: Java(TM) SE Runtime Environment 18.9 (11.0.20+9) (build 11.0.20+9-LTS-256)
# Java VM: Java HotSpot(TM) 64-Bit Server VM 18.9 (11.0.20+9-LTS-256, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# F:\opensource\myforks\jenkins\cdevents-plugin\hs_err_pid1916.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
#

**Comment by utkuertunc** [comment]
@rorybakerfmr Hey Rory, please check my PR about this issue. https://github.com/jenkinsci/cdevents-plugin/pull/11

**Comment by rorybakerfmr** [comment]
Looks good to me! Thank you
