### ISSUE TITLE
Should judge null when get jenkins http proxy setting

### ISSUE THREAD

**Issue by wuhuizuo** [jenkinsci/cdevents-plugin#9]
**Describe the bug**
when no http proxy setting, cd events failed to send by http sinker type.

**To Reproduce**

1. None http proxy setting on jenkins server.
2. Set http sinker type.
3. Run a job
4. view the jenkins system log.

**Expected behavior**

**Screenshots**
<img width="653" alt="image" src="https://github.com/jenkinsci/cdevents-plugin/assets/2574558/545babfa-da62-443f-9c50-c91de0efe8c3">

<img width="1032" alt="image" src="https://github.com/jenkinsci/cdevents-plugin/assets/2574558/526d8174-252f-4e32-903d-c4c0129b797a">

**Additional context**

- Jenkins version: `2.401.3`
- plugin version: [`1-24.v0250517580b_2`](https://github.com/jenkinsci/cdevents-plugin/releases/tag/1-24.v0250517580b_2)
- Problem code lines: https://github.com/jenkinsci/cdevents-plugin/blob/2780c2d1d9c9e19310763579c52fdd3b71c3b6ee/src/main/java/io/jenkins/plugins/cdevents/sinks/HttpSink.java#L29-L30

**Comment by rorybakerfmr** [comment]
Good summary and pull request - we have accepted these changes. Thank you!
